### ISSUE TITLE
class file for com.github.angeschossen.pluginframework.api.events.ExpressionEntity not found

### ISSUE THREAD

**Issue by Ixf1nity** [IncrediblePlugins/LandsAPI#21]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Hp/IdeaProjects/ClanNexus/src/main/java/in/arcadelabs/clanexus/nexus/Nexus.java:[34,42] cannot access com.github.angeschossen.pluginframework.api.events.ExpressionEntity
  class file for com.github.angeschossen.pluginframework.api.events.ExpressionEntity not found
[INFO] 1 error
[INFO] -------------------------------------------------------------

**Comment by Angeschossen** [comment]
Fixed

**Comment by Indyuce** [comment]
Hey, still having this issue using LandsAPI 6.28.11 - I've checked the wiki, it doesn't seem like I need any other dependency to use LandsAPI as dependency. It seems like the LandPlayer class extends the `ExpressionEntity` class which is not present in the API build.
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Jules/git/bounty-hunters/src/main/java/net/Indyuce/bountyhunters/compat/interaction/external/LandsSupport.java:[23,36] cannot access com.github.angeschossen.pluginframework.api.events.ExpressionEntity
  class file for com.github.angeschossen.pluginframework.api.events.ExpressionEntity not found
```
